export default {
  checkBox: "check box",
  city: "city",
  color: "color",
  country: "country",
  creditNoteForm: "credit_note_form",
  currentDate: "current date",
  date: "date",
  document: "document",
  dropdown: "dropdown",
  expireDate: "expire date",
  float: "float",
  form: "form",
  image: "image",
  location: "location",
  number: "number",
  password: "password",
  signature: "signature",
  state: "state",
  string: "string",
  text: "text",
  time: "time",
  totalTime: "total time",
};
